deployConfiguration: 
                 persistenceConfig:
                            persistenceProperties:
                                          hibernate.show_sql: "true"
                 poolConfig: 
                            poolProperties: 
                                          checkoutTimeout: "2000"
                                          maxStatements: "55"
                                          numHelperThreads: "3"